In [1]:
import torch
from torchvision.models import resnet18, ResNet18_Weights
model = resnet18(weights=ResNet18_Weights.DEFAULT)
data = torch.rand(1, 3, 64, 64)
labels = torch.rand(1, 1000)

Downloading: "https://download.pytorch.org/models/resnet18-f37072fd.pth" to C:\Users\lewibs/.cache\torch\hub\checkpoints\resnet18-f37072fd.pth
100.0%


In [32]:
prediction = model(data)
loss = (prediction - labels).sum()
print(loss)
loss.backward()

tensor(-482.8080, grad_fn=<SumBackward0>)


In [35]:
optim = torch.optim.SGD(model.parameters(), lr=1e-2, momentum=0.9)

In [38]:
optim.step()

In [40]:
import torch

a = torch.tensor([2., 3.], requires_grad=True)
b = torch.tensor([6., 4.], requires_grad=True)

Q = 3*a**3 - b**2



tensor([2., 3.], requires_grad=True)
tensor([6., 4.], requires_grad=True)
tensor([-12.,  65.], grad_fn=<SubBackward0>)


In [ ]:
external_grad = torch.tensor([1., 1.])
print(external_grad)
#Q.backward(gradient=external_grad)